#define LBRACE                           1
#define RBRACE                           2
#define COMMA                            3
#define STRING                           4
#define COLON                            5
#define IDENTIFIER                       6
#define LBRACKET                         7
#define RBRACKET                         8
#define NUMBER                           9
#define TRUE                            10
#define FALSE                           11
#define NULL_VAL                        12
